version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
volumes:
  postgres_data:
